### ISSUE TITLE
Simplify setup

### ISSUE THREAD

**Issue by SillyInventor** [CSnap/rpi_csdt_community#121]
@chuck211991 wants to simplify setup of the development environment. Has a pull request #120 .

I like the idea of having a bash script that runs through the install for python, libpq, etc. However, I am not really sure I understand the need for a virtualbox to ssh into for dev. Why is that better than virtual env?

**Comment by chuck211991** [comment]
There are a myriad of reasons we would want to use Vagrant rather than just python virtualev, such as:

- It can be used for deployment almost as easily as it can be used for development; Josh (HASS dev ops engineer) has suggested we use it as it will make his job a bit easier
- We will all be developing on a platform as close to production as possible; currently, development is done with a sqlite database, which may make it easy to miss postgresql related issues (this becomes especially important for the engineers who will be working on the GIS app)
- It super easy to run "vagrant up", versus trying to install all the Python depends through virtualenv. 
- It forces everyone to use the same operating system, architecture (in the sense of 64-bit), and software versions. This will reduce the possibility of "it didn't work on my machine"

Really, what it boils down to is us needing to simplify the setting up for development. As we onboard more developers, the shorter we can make that phase for them, the more productive they will be. It will not get much easier than Vagrant.

And a quick mention about why we are using Vagrant, and not just VirtualBox:

- Vagrant provides small base images, and we install a small amount of data on top of them. This means we won't need to download a new VM image everytime it's updated; the COW filesystem just gets updated
- Support for multiple host operating systems, including extensive community support for trouble shooting
- Automatic updates to the base image save us time in sysadmin

**Comment by SillyInventor** [comment]
Copied from email:
I need to test the new setup procedure more thoroughly before accepting your pull. In general, I'm not thrilled by the change because it means more work for me, it takes a while for vagrant up to process, it should run on multiple environments if it's well designed, and I don't particularly care about gis. However your argument about having the same database as the server is compelling.

Referenced in #122

**Comment by SillyInventor** [comment]
Also, to clarify, I did try vagrant, but I ran out of paid time for testing it on Friday, and today I am helping Ryan set up.

**Comment by chuck211991** [comment]
The trouble is that we can't spend time helping everyone setup; it becomes all of our time (setting up Ryan probably took a few hours, and setting up the undergraduates will take longer... I already spent about an hour helping Matt setup for GIS development last week)

In regards to running in multiple environments being a criteria for quality; in this case, I don't think it is necessary that we TEST every possible configuration, since the only instance that matters is community.csdt.rpi.edu, and that instance runs on a Ubuntu server. Any work spent getting stuff working on a Windows, Arch Linux, or Fedora installation does not make value for the end user; it just gets cut. It would be more valuable to test multiple web browsers and systems.

It takes ~5 minutes to vagrant up for the first time on my laptop and desktop. After that, it takes around 20-30 seconds. The first time is largely limited by download speed, since we are doing the apt install and pip install commands.

As for creating work for you, I hope it doesn't make too much. Please let me know if you encounter a problem that takes more than 5 minutes to solve.

Setting up on my Windows installation on the desktop (first time. so I had just cloned the repo and didn't have anything installed except Vagrant, which I use for other projects... it took a tad longer than I'd like, not sure why, but required no user intervention; I worked on a paper outline while it ran)
```
C:\Users\Charles\Programming\rpi_csdt_community>time /t
16:34

C:\Users\Charles\Programming\rpi_csdt_community>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/xenial64'...
.....
==> default: You should consider upgrading via the 'pip install --upgrade pip' command.

C:\Users\Charles\Programming\rpi_csdt_community>
C:\Users\Charles\Programming\rpi_csdt_community>
C:\Users\Charles\Programming\rpi_csdt_community>time /t
16:55
```

Starting after installation done
```
C:\Users\Charles\Programming\rpi_csdt_community>vagrant halt
==> default: Attempting graceful shutdown of VM...

C:\Users\Charles\Programming\rpi_csdt_community>
C:\Users\Charles\Programming\rpi_csdt_community>time /t
16:58

C:\Users\Charles\Programming\rpi_csdt_community>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/xenial64' is up to date...
==> default: A newer version of the box 'ubuntu/xenial64' is available! You currently
==> default: have version '20170104.0.0'. The latest is version '20170224.0.0'. Run
==> default: `vagrant box update` to update.
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 8000 (guest) => 8000 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: ubuntu
    default: SSH auth method: password
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/Charles/Programming/rpi_csdt_community
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

C:\Users\Charles\Programming\rpi_csdt_community>time /t
16:59
```

**Comment by SillyInventor** [comment]
You will get no argument from me on the value of simplifying setup. I'm only concerned about how.

I don't think that we should test any configuration other than our own. But having people building it on Windows 10, Ubuntu, Arch etc. might help keep the work accessible for the open source community. 

Testing with multiple browsers is important but the two are not necessarily exclusive.

I found that it took me longer than 5 min, because I had to look up installation for Vagrant, VirtualBox, Putty, PuttyGen (which apparently has to be gotten via make), figure out my ssh key situation, and start the setup of the dev environment. It took a while as I've not had to do that before.

With the exception of a hiccup with the aliasing to python 3 and installing npm but not node, Ryan's install was fairly smooth. Similar setup times I'd say.

Again, I agree your database argument is compelling enough to switch, but I haven't finished checking.
