### ISSUE TITLE
Consolidate Requirements

### ISSUE THREAD

**Issue by SillyInventor** [CSnap/rpi_csdt_community#125]
We should consolidate libraries, gis, heroku, and vcs to requirements. We should also probably see if we can't trim any libraries we currently install (as it can take a fairly long time). May depend on switching to postgres in #121.

**Comment by chuck211991** [comment]
We can ditch heroku, and should only need to take a library or two from gis. The VCS one is a bit more problematic, since those are libraries that got updated but hadn't made it into pip when we were looking to update the live site. If we see which libraries are there, some we can manually put into pypi (django_teams), others we may be able to get rid of.

**Comment by SillyInventor** [comment]
My plan is:

- Delete heroku
- Merge vcs, gis, and plain libraries into requirements
- Pair down the requirements
- Upgrade what's left
- Setup https://requires.io/

After that, setup should be complete, fast, and we should stay up to date.
